services:
  salary-calculator:
    build:
      context: .
      pull: false
    image: salary-calculator
    networks:
      - fintrack-network

networks:
  fintrack-network:
    external: true
    name: fintrack-network
